/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package space.jaggard.yogaforposers;

import space.jaggard.yogaforposers.program.Program;

public class App {

    public static void main(String[] args) {
        Program program = new Program();
        program.go();
    }

    public String isRunning(){
        return "App is running!";
    }
}
