/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package space.jaggard.yogaforposers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appIsRunning() {
        App app = new App();
        assertNotNull(app.isRunning(), "App should be able to start.");
    }
}
